### ISSUE TITLE
Practice template has correct number of quiz links - Follow Table in comment

### ISSUE THREAD

**Issue by Gwinert** [byuitechops/english-connect#34]

**Comment by meeple142** [comment]
these are the number of links we need
![image](https://cloud.githubusercontent.com/assets/10274976/25592882/a96568cc-2e77-11e7-8977-5960948e1f6a.png)

**Comment by meeple142** [comment]
here are csvs that are the same data
t10,S,R,W,L
1,4,10,1,10
2,3,10,1,10
3,3,5,1,5
4,4,5,1,5

t1,S,R,W,L
1,7,10,1,10
2,4,10,1,10
3,3,5,1,5
4,3,5,1,5
