### ISSUE TITLE
Check latest commit for issues?

### ISSUE THREAD

**Issue by didymusbenson** [byuitechops/english-connect#37]
I came in today, did a pull to get up to date, then made a push. I want to make sure I didn't break anything.

**Comment by meeple142** [comment]
I realize realized the node modules folder was included in the repository so I removed it from all of the history of the Repository not remembering that would probably mess up all of your copies until after I did it. The repository is over 30 Megs so I was trying to cut it down and it did technically make it smaller but it didn't make a dent and the 30 Megs. What was the problem? When you pull you might have to run 'npm i' to get the node modules back

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by didymusbenson** [comment]
I'm rolling back my commit to 8d8c0becb3e136aa8e7d3e77c21b3ffcf1540900 which is Ben's latest.

**Comment by didymusbenson** [comment]
fixed
